name: build-ubuntu
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  asgard-core:
# no MPI/CUDA but on CPU with OpenBlas and HDF5
# some BALS is required, makes little sense to skip HDF5 (can't output anything)
    strategy:
      matrix:
        prec: [float, double, float\;double]
        compiler: [clang++-14, g++-11]
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Makedir
        working-directory: ${{runner.workspace}}/asgard
        run: cmake -E make_directory build
      - name: Configure
        working-directory: ${{runner.workspace}}/asgard/build
        run: cmake -DCMAKE_BUILD_TYPE=Release
                   -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
                   -DASGARD_PRECISIONS=${{matrix.prec}}
                   -DASGARD_BUILD_HDF5=ON
                   -DASGARD_RECOMMENDED_DEFAULTS=ON
                   ../
      - name: Build
        working-directory: ${{runner.workspace}}/asgard/build
        run: make -j VERBOSE=1
      - name: Test
        working-directory: ${{runner.workspace}}/asgard/build
        run: ctest --output-on-failure
      - name: Show Log
        if: failure()
        working-directory: ${{runner.workspace}}/asgard/build/Testing/Temporary
        run: cat LastTest.log
  asgard-mpi:
# basic MPI build using default settings
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: install
        working-directory: ${{runner.workspace}}/asgard
        run: sudo apt install -y libopenmpi-dev
      - name: Makedir
        working-directory: ${{runner.workspace}}/asgard
        run: cmake -E make_directory build
      - name: Configure
        working-directory: ${{runner.workspace}}/asgard/build
        run: cmake -DCMAKE_BUILD_TYPE=Release
                   -DASGARD_USE_MPI=ON
                   -DASGARD_RECOMMENDED_DEFAULTS=ON
                   ../
      - name: Build
        working-directory: ${{runner.workspace}}/asgard/build
        run: make -j VERBOSE=1
      - name: Test
        working-directory: ${{runner.workspace}}/asgard/build
        run: make test
      - name: Show Log
        if: failure()
        working-directory: ${{runner.workspace}}/asgard/build/Testing/Temporary
        run: cat LastTest.log
  asgard-mkl:
# maybe an overkill but there are some differences between MKL and OpenBlas
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: install
        working-directory: ${{runner.workspace}}/asgard
        run: |
             wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
             echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
             sudo apt update
             sudo apt install -y intel-oneapi-mkl-devel
      - name: Makedir
        working-directory: ${{runner.workspace}}/asgard
        run: cmake -E make_directory build
      - name: Configure
        working-directory: ${{runner.workspace}}/asgard/build
        run: cmake -DCMAKE_BUILD_TYPE=Release
                   -DASGARD_RECOMMENDED_DEFAULTS=ON
                   ../
      - name: Build
        working-directory: ${{runner.workspace}}/asgard/build
        run: make -j VERBOSE=1
      - name: Test
        working-directory: ${{runner.workspace}}/asgard/build
        run: make test
      - name: Show Log
        if: failure()
        working-directory: ${{runner.workspace}}/asgard/build/Testing/Temporary
        run: cat LastTest.log
